### ISSUE TITLE
Disconnected concept clusters

### ISSUE THREAD

**Issue by rbrownlee** [cmader/qSKOS#38]
Hi,

In the example hyperlinked below, I have two top concepts, each of which has a narrower concept.  The top concepts are related to each other, and the narrower concepts are related to each other.  The associative and hierarchical relationships are reciprocally expressed, as are the relationships between the top concepts and the concept scheme.  If I check the vocabulary with qSKOS (either through http://qskos.poolparty.biz/ or by local use of the software) I get a report of disconnected concept clusters, "sets of concepts that are isolated from the rest of the vocabulary."  

Example vocabulary
https://drive.google.com/open?id=0B57_4U1eo8d3WVBFSXRKUW42WHc

qSKOS report via http://qskos.poolparty.biz/
https://drive.google.com/open?id=0B57_4U1eo8d3OFBOZzc1aEFKX28

I'd appreciate your thoughts on this. I don't understand why qSKOS is flagging this issue, and so am unable to explain it to others when asked why this is happening.  I work for an organisation which provides a vocabulary service (ANDS - Australian National Data Service).  We routinely recommend that people check files via qSKOS prior to upload, and have had enquiries concerning this topic.

thanks
rowan

**Comment by cmader** [comment]
Hi Rowan,

Thanks for reporting. I will look into this in detail as soon as possible and
get back to you.

best,
Christian

**Comment by cmader** [comment]
The report generation for disconnected concept clusters concept clusters contained a bug which caused correct vocabularies (like the one provided by you) to fail. This has been now fixed in version 1.4.8 in the master branch.

**Comment by rbrownlee** [comment]
Hi Christian - I appreciate your follow-up on this and I'll be interested to compare results.

bye
rowan
