### ISSUE TITLE
Test `invokeOnCmdLine` does not run on non-*nix systems due to hard-coded path

### ISSUE THREAD

**Issue by larsgsvensson** [cmader/qSKOS#47]
The test [invokeOnCmdLine](https://github.com/cmader/qSKOS/blob/d8bfcfd1eb288a2cafabb6197f7cead95a4f55a7/src/test/java/at/ac/univie/mminf/qskos4j/cmd/IssueInvocationTest.java#L19) has the path `/tmp/testreport` hard-coded so the test will not run on a windows system.
I suggest to use `Files.createTempFile` instead as stated in my pull request #44

**Comment by cmader** [comment]
Thanks for the pull request. Merged into master and created a new release.
